name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /home/runner/android-sdk
      ANDROID_HOME: /home/runner/android-sdk
      PATH: /home/runner/android-sdk/cmdline-tools/latest/bin:/home/runner/android-sdk/platform-tools:/usr/bin:/bin
      BUILDOZER_SDKMANAGER: /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies and build APK
        run: |
          chmod +x setup_android.sh
          ./setup_android.sh
          buildozer android debug
